  $ ocaml-bindgen empty.h empty
  $ cat dune
  
  ; automatically generated by ocaml-bindgen 0.0.1
  (library
   (name empty)
   (foreign_stubs
    (language c)
    (names caml_empty.c)
    (flags
     (:standard -O2))))
  
  $ cat empty.ml
  (* automatically generated by ocaml-bindgen 0.0.1 *)
  
  $ cat caml_empty.c
  /* automatically generated by ocaml-bindgen 0.0.1 */
  
