let write_file pp content file =

  let oc = open_out file in
  let fmt = Format.formatter_of_out_channel oc in
  Format.fprintf fmt "(* automatically generated by ocaml-bindgen 0.0.1 *)\r\n";
  Format.fprintf fmt "%a\r\n%!" pp content;
  close_out oc;
  ()

let write_caml_files caml file =
  write_file Pprintast.structure caml file

let write_c_files (c: Clang.Ast.translation_unit) file =
  write_file Clang.Printer.translation_unit c file
