  $ ocaml-bindgen struct.h struct
  $ cat dune
  
  ; automatically generated by ocaml-bindgen 0.0.1
  (library
   (name empty)
   (foreign_stubs
    (language c)
    (names caml_empty.c)
    (flags
     (:standard -O2))))
  
  $ cat struct.h
  $ cat struct.ml
  (* automatically generated by ocaml-bindgen 0.0.1 *)
  
  $ cat caml_struct.c
  /* automatically generated by ocaml-bindgen 0.0.1 */
  
