  $ ocaml-bindgen struct.h struct
  $ cat dune
  
  ; automatically generated by ocaml-bindgen 0.0.1
  (library
   (name struct)
   (foreign_stubs
    (language c)
    (names caml_struct.c)
    (flags
     (:standard -O2))))
  
  $ cat struct.h
  typedef struct Doggo {
      int many;
      char wow;
  } Doggo;
  $ cat struct.ml
  (* automatically generated by ocaml-bindgen 0.0.1 *)
  type nonrec doggo = {
    many: int ;
    wow: char }
  $ cat caml_struct.c
  /* automatically generated by ocaml-bindgen 0.0.1 */
  Doggo* caml_Doggo_of_value(struct value* caml_x) {
    Doggo* x = malloc(sizeof(struct Doggo));
    caml_x = caml_alloc_tuple(2);
    Store_field(caml_x, 0, Val_int(x->many));
    Store_field(caml_x, 1, Val_int(x->wow));
    CAMLreturn(caml_x)
  }
  
  value caml_Doggo_to_value(struct Doggo* x) {
    CAMLparam0();
    CAMLlocal1(caml_x);
    caml_x = caml_alloc_tuple(2);
    Store_field(caml_x, 0, Val_int(x->many));
    Store_field(caml_x, 1, Val_int(x->wow));
    CAMLreturn(caml_x)
  }
  
  
