  $ ocaml-bindgen libsql.h libsql
  $ cat dune
  
  ; automatically generated by ocaml-bindgen 0.0.1
  (library
   (name libsql)
   (foreign_stubs
    (language c)
    (names caml_libsql.c)
    (flags
     (:standard -O2))))
  
  $ cat libsql.ml
  (* automatically generated by ocaml-bindgen 0.0.1 *)
  type nonrec libsql_connection
  type nonrec libsql_database
  type nonrec libsql_row
  type nonrec libsql_rows
  type nonrec libsql_rows_future
  type nonrec libsql_stmt
  $ cat caml_libsql.c
  /* automatically generated by ocaml-bindgen 0.0.1 */
  
