  $ ocaml-bindgen libsql.h libsql
  $ cat dune
  
  ; automatically generated by ocaml-bindgen 0.0.1
  (library
   (name libsql)
   (foreign_stubs
    (language c)
    (names caml_libsql.c)
    (flags
     (:standard -O2))))
  
  $ cat libsql.ml
  (* automatically generated by ocaml-bindgen 0.0.1 *)
  type a
  type a
  type a
  type a
  type a
  type a
  type a
  type a
  $ cat caml_libsql.c
  /* automatically generated by ocaml-bindgen 0.0.1 */
  struct  {
                                                        };
                                                        struct
                                                        libsql_connection {
                                                        };
                                                        struct libsql_database
                                                        {
                                                        };
                                                        struct libsql_row {
                                                        };
                                                        struct libsql_rows {
                                                        };
                                                        struct
                                                        libsql_rows_future {
                                                        };
                                                        struct libsql_stmt {
                                                        };
                                                        struct  {
                                                        };
                                                        
