(* automatically generated by ocaml-bindgen 0.0.1 *)
type nonrec doggo = {
  many: int ;
  wow: char }
external eleven_out_of_ten_majestic_af :
  pupper:doggo -> unit = "caml_eleven_out_of_ten_majestic_af"
