(* automatically generated by ocaml-bindgen 0.0.1 *)
type nonrec breed =
  | Labrador 
  | UnderGoldenRetriever 
  | Pug 
  | UnderPoodle 
type nonrec doggo = {
  many: int ;
  breed: breed ;
  wow: char }
external eleven_out_of_ten_majestic_af :
  pupper:doggo -> unit = "caml_eleven_out_of_ten_majestic_af"
